#![allow(non_upper_case_globals)]

py_exception!(lumol, LumolError);
